



















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `connstr`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=.\SQLEXPRESS;Database=RoutingSlipsSample;Trusted_Connection=True;`
//     Schema:                 ``
//     Include Views:          `False`

using System;

namespace Models
{
    
    public partial class Component_A 
    {
		public Guid id { get; set; }
		public Guid? batchid { get; set; }
	}
    
    public partial class Component_B 
    {
		public Guid id { get; set; }
		public Guid? batchid { get; set; }
	}
    
    public partial class Widget 
    {
		public Guid id { get; set; }
		public Guid? component_a_id { get; set; }
		public Guid? component_b_id { get; set; }
		public string Name { get; set; }
		public DateTime CreatedDate { get; set; }
		public DateTime ModifiedDate { get; set; }
	}
}
